### PR TITLE
fix: (esx_skin & esx_menu_default) Close menu

### PR DESCRIPTION
**Pull request by Cartman117**
If close function is called multiple times for the same menu, we are stuck in the menu on the second opened one.

This is related to this issue #689

### CODE REVIEW

**Comment by Cartman117** [comment]
Sorry I misunderstood esx_skin, the second close call was initiated by esx_barbarshop or clotheshop.
I didn't check if other shops using esx_skin also have this problem.

**Comment by CsokiHUN** [comment]
solution to problem #822 as well?

**Comment by Gellipapa** [comment]
Hi! @Cartman117 Please fix merge conflict. Thank you for help.

**Comment by Cartman117** [comment]
> Hi! @Cartman117 Please fix merge conflict. Thank you for help.

Hi, It's done

**Pull request closed without merging**
